version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        dependency-type: production
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        dependency-type: production
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        dependency-type: production
