version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        dependency-type: production
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      docker:
        dependency-type: production
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: monthly
    groups:
      docker-compose:
        dependency-type: production
