# -*- mode: yaml; coding: utf-8 -*-
#
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
# Workflow to publish the Docker image to Docker Hub.

name: Publish Docker image to Docker Hub

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read

jobs:
  Publish-DockerHub:
    name: Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment:
      name: Docker Hub
      url: https://hub.docker.com/r/btschwertfeger/infinity-grid
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # IMPORTANT: otherwise the current tag does not get fetched and the build version gets worse

      - name: Download Docker image artifact
        uses: actions/download-artifact@v5
        with:
          name: docker-image
          path: ${{ runner.temp }}

      - name: Load Docker image
        run: docker load --input ${{ runner.temp }}/infinity-grid-image.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Tag and push to Docker Hub
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          echo "$TAGS" | while IFS= read -r tag; do
            docker tag btschwertfeger/infinity-grid:build-artifact "$tag"
            docker push "$tag"
          done
