# -*- mode: yaml; coding: utf-8 -*-
#
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
# Template workflow to run the tests.
#

name: Test

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      python-version:
        type: string
        required: true

permissions:
  contents: read

jobs:
  Test:
    name: Test ${{ inputs.os }} ${{ inputs.python-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@28f2168f4d98ee0445e3c6321f6e6616c83dd5ec # v5.3.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Download the built wheel
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: python-package-distributions
          path: dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install package (Linux or macOS)
        if: runner.os != 'Windows'
        run: |
          uv venv
          source .venv/bin/activate
          echo ${GITHUB_WORKSPACE}/.venv/bin >> $GITHUB_PATH
          uv pip install "$(find dist -name '*.whl' | head -1)" -r requirements-dev.txt

      - name: Install package (Windows)
        if: runner.os == 'Windows'
        run: |
          uv venv
          .venv\Scripts\activate.ps1
          echo "$env:GITHUB_WORKSPACE\.venv\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          $wheel = (Get-ChildItem -Path dist -Filter "*.whl" | Select-Object -First 1).FullName
          uv pip install "$wheel" -r requirements-dev.txt

      - name: Run the tests
        run: pytest -vv -x -n auto tests
