# -*- mode: yaml; coding: utf-8 -*-
#
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# All rights reserved.
# https://github.com/btschwertfeger
#
#

name: Cleanup untagged layers in GitHub Container Registry

on:
  schedule:
    - cron: "0 3 1 * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete untagged images from GHCR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: btschwertfeger
          PACKAGE: infinity-grid
        run: |
          # Fetch untagged versions (up to 100 latest)
          versions=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/$OWNER/packages/container/$PACKAGE/versions?per_page=100 \
            --jq '.[] | select(.metadata.container.tags | length == 0) | .id')

          if [ -z "$versions" ]; then
            echo "No untagged images found."
            exit 0
          fi

          echo "Deleting untagged image versions:"
          for id in $versions; do
            echo " - Deleting version $id"
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /users/$OWNER/packages/container/$PACKAGE/versions/$id
          done
